---
version: '3.3'

volumes:
  pg-data:

services:
  nerves_hub_api:
    image: nerves_hub_api:latest
    hostname: api.nerves-hub.org
    ports:
      - 4444:4444
    environment:
      HOST: api.nerves-hub.org
      PORT: 4444
      DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
      CA_HOST: ca.nerves-hub
      NERVESHUB_SSL_KEY: "/etc/ssl/nerveshub/root-ca-key.pem"
      NERVESHUB_SSL_CERT: "/etc/ssl/nerveshub/root-ca.pem"
      NERVESHUB_SSL_CACERT: "/etc/ssl/nerveshub/ca.pem"
      NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
    volumes:
      - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  nerves_hub_device:
    image: nerves_hub_device:latest
    hostname: device.nerves-hub.org
    ports:
      - 4445:4445
    environment:
      HOST: device.nerves-hub.org
      PORT: 4445
      DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
      CA_HOST: ca.nerves-hub
      NERVESHUB_SSL_KEY: "/etc/ssl/nerveshub/root-ca-key.pem"
      NERVESHUB_SSL_CERT: "/etc/ssl/nerveshub/root-ca.pem"
      NERVESHUB_SSL_CACERT: "/etc/ssl/nerveshub/ca.pem"
      NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
    volumes:
      - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  nerves_hub_www:
    image: nerves_hub_www:latest
    hostname: www.nerves-hub.org
    ports:
      - 8080:4000
    environment:
      HOST: nerves-hub.org
      PORT: 80
      DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
      SECRET_KEY_BASE: "03285X8MQ01dU8oO56pnpwgnL4eH70sTohga1bFb2mu/UKlkswnkGN9D/ZLLpgwX"
      LIVE_VIEW_SIGNING_SALT: "U7UeQwpezh0Fm5U7ZvuWm99ttXzuFC9TyoftI2Edmw4Yo0L7EKRtMvdm8UFJ7LS0"
      NERVESHUB_SSL_KEY: "/etc/ssl/nerveshub/root-ca-key.pem"
      NERVESHUB_SSL_CERT: "/etc/ssl/nerveshub/root-ca.pem"
      NERVESHUB_SSL_CACERT: "/etc/ssl/nerveshub/ca.pem"
      NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
    volumes:
      - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  postgres:
    image: postgres:10-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
      PGDATA: /data
    volumes:
      - pg-data:/pg-data
